### ISSUE TITLE
efa

### ISSUE THREAD

**Issue by Dura-Europos** [wangh107/lavaan#3]
Validate `efa()` function

Reference:

- Tutorial: https://lavaan.ugent.be/tutorial/efa.html#exploratory-factor-analysis-efa
- Documentation: https://github.com/yrosseel/lavaan/blob/a271f07a212fcf2902352833a37bde2202eb6b00/man/efa.Rd
- Source code: https://github.com/yrosseel/lavaan/blob/6101ca2badec6da042b368bfe407cd9d683ac0a7/R/xxx_efa.R#L12

Example run from Ying-Fang
```
library(lavaan)
data = HolzingerSwineford1939
fit <- efa(data = data, 
           ov.names = paste("x", 1:9, sep = ""),
           nfactors = 1:3,
           rotation = "geomin",
           rotation.args = list(geomin.epsilon = 0.01, rstarts = 1))
summary(fit, nd = 3L, cutoff = 0.2, dot.cutoff = 0.05,
        lambda.structure = TRUE, pvalue = TRUE)
```

**Comment by laywang142** [comment]
Notes: 

No error tests: 
- Arguments from example
- Arguments but without defined ov.names
- Check if S4 type if output = "lavaan"
- Check that inputting sample covariance instead of data returns output (also check if it returns same-ish output as dataframe input)

Error tests: 
- Try to trigger as many errors as possible 
- note: some error messages might be for temporary things (such as grouping) as new features may show up later.
